---
title: "GMM_KS"
author: "Kee-Young Shin"
date: "4/29/2020"
output: html_document
---

```{r}
# Uses EM algorithm with multivariate normal
# distribution to estimate cluster probability
mvnorm_covinv = function(Sigma) {
  # Eigendecomposition of covariance matrix
  E = eigen(Sigma)
  Lambda_inv = diag(E$values^-1)   # diagonal matrix
  Q = E$vectors
  return(Q %*% Lambda_inv %*% t(Q))
}
# multivariate Gaussian pdf 
mvn_pdfi = function(xi, mu, Sigma)
  1/sqrt( (2*pi)^length(xi) * det(Sigma) ) * 
  exp(-(1/2) * t(xi - mu) %*% mvnorm_covinv(Sigma) 
  %*% (xi - mu))
# for all X
mvn_pdf = function(X, mu, Sigma)
  apply(X, 1, function(xi) mvn_pdfi(as.numeric(xi), mu, Sigma))

# function for clustering
gmm_clustering = function(X, k){
  p = ncol(X)  # number of parameters
  n = nrow(X)  # number of observations
  Delta = 1
  iter = 0
  itermax = 30
  while(Delta > 1e-4 && iter <= itermax){
    # initiation
    if(iter == 0){
      # use centroid from kmeans algorithm 
      km_init = kmeans_cluster(X, k)
      mu = km_init$centroid
      mu_mem = mu
      w = sapply(1:k, function(i) length(which(km_init$cluster == i)))
      # assign starting weights based on K means results
      w = w/sum(w)
      cov = array(dim = c(p, p, k))
      for(i in 1:p) for(j in 1:p) for(c in 1:k)
        # starting sigma matrices for mvn distribution 
        cov[i, j, c] = 
        1/n * sum((X[km_init$cluster == c, i] - mu[c, i]) *
        (X[km_init$cluster == c, j] - mu[c, j]))
    }
    
 # E-step
    mvn_c = sapply(1:k, function(c) mvn_pdf(X, mu[c,], cov[,, c]))
    # probability of point in cluster c 
    p_ic = t(w*t(mvn_c)) / rowSums(t(w*t(mvn_c)))
    
 # M-step
    n_c = colSums(p_ic)
    w = n_c/sum(n_c)
    mu = t(sapply(1:k, function(c) 1/n_c[c] * colSums(p_ic[, c] *
      X)))
    for(i in 1:p) for(j in 1:p) for(c in 1:k) 
      cov[i, j, c] =
      1/n_c[c] * sum(p_ic[, c] * (X[, i] - mu[c, i]) * p_ic[, c] *
      (X[, j] - mu[c, j]))
    Delta = sum((mu - mu_mem)^2)
    iter = iter + 1
    mu_mem = mu
  }
  return(list(softcluster = p_ic, cluster = apply(p_ic, 1,
    which.max)))
}

```

```{r}
# run for two clusters
gmm = gmm_clustering(fatalities_country_curves[,1:3], 2)
gmm$cluster
# run K-means
km1 <- kmeans_cluster(fatalities_country_curves[,1:3], 2)
pairs(cases_country_curves[,1:3], lower.panel = NULL, col = km$cluster)
summary(factor(km$cluster))
gmm$cluster
km1$cluster
```

```{r}
# created second EM algorithm to work with different dataset

mvnorm_covinv = function(Sigma) {
  # Eigendecomposition of covariance matrix
  E = eigen(Sigma)
  Lambda_inv = diag(E$values^-1)   # diagonal matrix
  Q = E$vectors
  return(Q %*% Lambda_inv %*% t(Q))
}
# multivariate Gaussian pdf 
mvn_pdfi = function(xi, mu, Sigma){
  deter = det(Sigma)
  deter = ifelse(deter<0, 0.001, deter)
  res = 1/sqrt( (2*pi)^length(xi) * deter ) * 
  exp(-(1/2) * t(xi - mu) %*% mvnorm_covinv(Sigma) 
  %*% (xi - mu))
  return(res)}
# for all X
mvn_pdf = function(X, mu, Sigma)
  apply(X, 1, function(xi) mvn_pdfi(as.numeric(xi), mu, Sigma))

# function for clustering
gmm_clustering = function(X, k){
  p = ncol(X)  # number of parameters
  n = nrow(X)  # number of observations
  Delta = 1
  iter = 0
  itermax = 30
  while(Delta > 1e-4 && iter <= itermax){
    # initiation
    if(iter == 0){
      # use centroid from kmeans algorithm 
      km_init = kmeans_cluster(X, k)
      mu = km_init$centroid
      mu_mem = mu
      w = sapply(1:k, function(i) length(which(km_init$cluster == i)))
      # assign starting weights based on K means results
      w = w/sum(w)
      cov = array(dim = c(p, p, k))
      for(i in 1:p) for(j in 1:p) for(c in 1:k)
        # starting sigma matrices for mvn distribution 
        cov[i, j, c] = 
        1/n * sum((X[km_init$cluster == c, i] - mu[c, i]) *
        (X[km_init$cluster == c, j] - mu[c, j]))
    }
    
 # E-step
    mvn_c = sapply(1:k, function(c) mvn_pdf(X, mu[c,], cov[,, c]))
    # probability of point in cluster c 
    p_ic = t(w*t(mvn_c)) / rowSums(t(w*t(mvn_c)))
    
 # M-step
    n_c = colSums(p_ic)
    w = n_c/sum(n_c)
    mu = t(sapply(1:k, function(c) 1/n_c[c] * colSums(p_ic[, c] *
      X)))
    for(i in 1:p) for(j in 1:p) for(c in 1:k) 
      cov[i, j, c] =
      1/n_c[c] * sum(p_ic[, c] * (X[, i] - mu[c, i]) * p_ic[, c] *
      (X[, j] - mu[c, j]))
    Delta = sum((mu - mu_mem)^2)
    iter = iter + 1
    mu_mem = mu
  }
  return(list(softcluster = p_ic, cluster = apply(p_ic, 1,
    which.max)))
}

```



```{r}
# trouble shooting...

# multivariate Gaussian pdf 
# issue with determinant being negative: sqrt of negative returns NA
mvn_pdfi = function(xi, mu, Sigma)
  deter = det(Sigma)
  deter = ifelse(deter<0, 0.001, deter)
  1/sqrt( (2*pi)^length(xi) * deter ) * 
  exp(-(1/2) * t(xi - mu) %*% mvnorm_covinv(Sigma) 
  %*% (xi - mu))
# for all X
mvn_pdf = function(X, mu, Sigma)
  apply(X, 1, function(xi) mvn_pdfi(as.numeric(xi), mu, Sigma))

1/sqrt( (2*pi)^length(fatalities_country_curves[1,1:3]) * 0.001 ) * 
  exp(-(1/2) * (as.matrix(fatalities_country_curves[1,1:3]) - mu[1]) %*% mvnorm_covinv(cov[,,1]) %*% t(fatalities_country_curves[1,1:3] - mu[1]))

# function for clustering
gmm_clustering = function(X, k){
  p = ncol(fatalities_country_curves[,1:3])  # number of parameters
  n = nrow(fatalities_country_curves[,1:3])  # number of observations
  Delta = 1
  iter = 0
  itermax = 30
  while(Delta > 1e-4 && iter <= itermax){
    # initiation
    if(iter == 0){
      # use centroid from kmeans algorithm 
      km_init = kmeans_cluster(fatalities_country_curves[,1:3], 2)
      mu = km_init$centroid
      mu_mem = mu
      w = sapply(1:2, function(i) length(which(km_init$cluster == i)))
      # assign starting weights based on K means results
      w = w/sum(w)
      cov = array(dim = c(p, p, 2))
      for(i in 1:p) for(j in 1:p) for(c in 1:2)
        # starting sigma matrices for mvn distribution 
        cov[i, j, c] = 
        1/n * sum((fatalities_country_curves[,1:3][km_init$cluster == c, i] - mu[c, i]) *
        (fatalities_country_curves[,1:3][km_init$cluster == c, j] - mu[c, j]))
    }
    
 # E-step
    mvn_c = sapply(1:2, function(c) mvn_pdf(fatalities_country_curves[,1:3], mu[c,], cov[,, c]))
    # probability of point in cluster c 
    p_ic = t(w*t(mvn_c)) / rowSums(t(w*t(mvn_c)))
    
 # M-step
    n_c = colSums(p_ic)
    w = n_c/sum(n_c)
    mu = t(sapply(1:k, function(c) 1/n_c[c] * colSums(p_ic[, c] *
      X)))
    for(i in 1:p) for(j in 1:p) for(c in 1:k) 
      cov[i, j, c] =
      1/n_c[c] * sum(p_ic[, c] * (X[, i] - mu[c, i]) * p_ic[, c] *
      (X[, j] - mu[c, j]))
    Delta = sum((mu - mu_mem)^2)
    iter = iter + 1
    mu_mem = mu
  }
  return(list(softcluster = p_ic, cluster = apply(p_ic, 1,
    which.max)))
}
```

```{r}

delta = function(X, pars){
  phi1 = dmvnorm(X, mean = pars[1], sigma = pars[2])
}
# E-step evaluating conditional means E(Z_i | X_i , pars)
delta <- function(X, pars){
  phi1 <- dnorm(X, mean=pars$mu1, sd=pars$sigma1)
  phi2 <- dnorm(X, mean=pars$mu2, sd=pars$sigma2)
  return(pars$p * phi2 / ((1 - pars$p) * phi1 + pars$p * phi2))
}
```

